# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install zenodo_get
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install brukerapi
      run: |
        git clone https://github.com/isi-nmr/brukerapi-python.git
        cd brukerapi-python
        python setup.py build
        python setup.py install

    - name: Test using the PV5.1 test data set
      run: |
        cd brukerapi-python/test
        zenodo_get 10.5281/zenodo.3899268
        unzip 0.2H2.zip
        python -m pytest --test_data "0.2H2" --test_config "config/auto_test_pv51.json" -v

    - name: Test using the bruker2nifti_qa data set
      run: |
        cd brukerapi-python/test
        git clone https://gitlab.com/naveau/bruker2nifti_qa.git
        python -m pytest --test_data bruker2nifti_qa/raw --test_config config/auto_test_qa.json -v

    - name: Test using the PV6.0.1 test data set
      run: |
        cd brukerapi-python/test
        zenodo_get 10.5281/zenodo.3894651
        unzip 20200612_094625_lego_phantom_3_1_2.zip
        python -m pytest --test_data "" --test_config "config/auto_test_pv601.json" -v